language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER='g++-7' BUILD_TYPE='Debug' BENCHMARKS='OFF'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER='g++-7' BUILD_TYPE='Release' BENCHMARKS='ON'

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libstdc++-8-dev
      env: COMPILER='clang++-6.0' BUILD_TYPE='Debug' BENCHMARKS='OFF'

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libstdc++-8-dev
      env: COMPILER='clang++-6.0' BUILD_TYPE='Release' BENCHMARKS='ON'

install:
  - THIRDPARTY_DIR="${TRAVIS_BUILD_DIR}/thirdparty"
  - mkdir -p ${THIRDPARTY_DIR}
  - cd ${THIRDPARTY_DIR}
  - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
  - mkdir cmake
  - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${THIRDPARTY_DIR}/cmake/bin:${PATH}

script:
  - BUILD_DIR=${TRAVIS_BUILD_DIR}/build/${COMPILER}/${BUILD_TYPE}
  - SRC_DIR=${TRAVIS_BUILD_DIR}
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DVT_ENABLE_BENCHMARKS=${BENCHMARKS} ${SRC_DIR}
  - make -j2 VERBOSE=1
  - ./vt-ndarray-test
